"""
The scripts loads a VMEC configuration constructs a surface at specified s, and then builds a new VMEC with that surface as LCFS.
"""
from datetime import datetime
import os
from pathlib import Path
import numpy as np
from simsopt.mhd import Vmec, Boozer
from simsopt.mhd.vmec_diagnostics import Struct, vmec_splines


# --- Helper to write VMEC input file from Fourier coefficients ---
def write_vmec_input_from_coeffs(filename, xm, xn, rmnc, zmns, rax_cc, zax_cs, nfp, params=dict(), comments = ""):
    """
    Write a minimal VMEC input file with boundary coefficients.
    Only writes the boundary section (RBC, ZBS) and a few required parameters.
    """
    # Check certain key parameters are passed
    key_params = ["nfp", "mpol", "ntor"]
    for param in key_params:
        if param not in params:
            raise ValueError(f"Missing required parameter: {param}")

    # Write to VMEC file
    file_object = open(filename,"w+")
    file_object.write(f"! This &INDATA namelist was generated by considering existing VMEC.\n")
    file_object.write("! Date: "+datetime.now().strftime("%B %d, %Y")+", Time: "+datetime.now().strftime("%H:%M:%S")+" UTC"+datetime.now().astimezone().strftime("%z")+"\n")
    file_object.write(f"! {str(comments)} "+"\n")
    

    file_object.write('!----- Runtime Parameters -----\n')
    file_object.write('&INDATA\n')
    file_object.write('  DELT = '+str(params.get("delt", 0.9))+'\n')
    file_object.write('  NSTEP = '+str(params.get("nstep", 200))+'\n')
    file_object.write('  TCON0 = '+str(params.get("tcon0", 2.0))+'\n')
    file_object.write('  NS_ARRAY = '+str(params.get("ns_array", [16,49,101]))[1:-1]+'\n')
    file_object.write('  FTOL_ARRAY = '+str(params.get("ftol_array", [1e-14,1e-13,1e-13]))[1:-1]+'\n')
    file_object.write('  NITER_ARRAY = '+str(params.get("niter_array", [2000,2000,2000]))[1:-1]+'\n')
    if 'lbsubs' in params.keys():
        file_object.write('  LBSUBS = '+str(params.get("lbsubs", "False"))+'\n')
    file_object.write("  PRECON_TYPE = '"+str(params.get("precon_type", 'NONE'))+"'\n")
    file_object.write('  PREC2D_THRESHOLD = '+str(params.get("precon_thresh", 1.00000e-30))+'\n')
    if "pre_niter" in params.keys():
        file_object.write('  PRE_NITER = '+str(params.get("pre_niter", 1000))+'\n')

    file_object.write('!----- Grid Parameters -----\n')
    file_object.write('  LASYM = '+str(bool(params.get("lasym", "False")))+'\n')
    file_object.write('  NFP = '+str(nfp)+'\n')
    file_object.write('  MPOL = '+str(params.get("mpol"))+'\n')
    file_object.write('  NTOR = '+str(params.get("ntor"))+'\n')
    file_object.write('  PHIEDGE = '+str(params.get("phiedge", 1.0))+'\n')

    file_object.write('!----- Pressure Parameters -----\n')
    file_object.write('  PRES_SCALE = '+str(params.get("pres_scale", 1.0))+'\n')
    file_object.write("  PMASS_TYPE = '"+params.get("pmass_type", "power_series")+"'\n")
    file_object.write('  AM = '+str(params.get("am", [0.0, -0.0]))[1:-1]+'\n')
    file_object.write('!----- Free Boundary Parameters -----\n')
    file_object.write('  LFREEB = F\n')
    file_object.write('!----- Current/Iota Parameters -----\n')
    file_object.write('  CURTOR = '+str(params.get("curtor", 0.0))+'\n')
    file_object.write('  NCURR = '+str(params.get("ncurr", 1))+'\n')
    file_object.write("  PCURR_TYPE = '"+params.get("pcurr_type", "power_series")+"'\n")
    file_object.write('  AC = '+str(params.get("ac", [1]))[1:-1]+'\n')

    file_object.write('!----- Axis Parameters -----\n')
    # To convert sin(...) modes to vmec, we introduce a minus sign. This is because in vmec,
    # R and Z ~ sin(m theta - n phi), which for m=0 is sin(-n phi) = -sin(n phi).
    file_object.write('  RAXIS_CC = '+str(rax_cc)[1:-1]+'\n')
    file_object.write('  ZAXIS_CS = '+str(-np.array(zax_cs))[1:-1]+'\n')

    file_object.write('!----- Boundary Parameters -----\n')
    for j, (m, n) in enumerate(zip(xm, xn)):
        file_object.write(    '  RBC('+f"{int(n/nfp):03d}"+','+f"{int(m):03d}"+') = '+f"{rmnc[j]:+.16e}"+',    ZBS('+f"{int(n/nfp):03d}"+','+f"{int(m):03d}"+') = '+f"{zmns[j]:+.16e}"+'\n')
    file_object.write('/\n')
    file_object.close()

def create_downsampled_cases(wout_name, s_target, target_dir="./", only_folders=False, vmec_file=None):
    # Check the s_target is a list
    if not isinstance(s_target, list):
        s_target = [s_target]

    if only_folders:
        file_list = []
        for s in s_target:
            dir = target_dir + f"regcoil_scan_results_{wout_name}_s_target_{s:.2f}/"
            if not os.path.exists(dir):
                os.makedirs(dir)
            file_list.append(dir)
        return file_list

    # Load reference wout equilibrium only when generating new VMEC inputs.
    if vmec_file is None:
        default_vmec = Path(target_dir).resolve().parent / f"wout_{wout_name}.nc"
        vmec_file = str(default_vmec)
    if not os.path.isfile(vmec_file):
        raise FileNotFoundError(
            f"VMEC file not found: {vmec_file}. Pass vmec_file=... to create_downsampled_cases()."
        )

    vmec = Vmec(vmec_file)
    vs = vmec_splines(vmec)
    print(f"Number of surfaces: {vmec.wout.ns}")

    # Stellarator symmetry
    lasym = getattr(vmec.wout, 'lasym', False)
    if lasym:
        raise NotImplementedError("This script currently only supports stellarator-symmetric configurations. Please set lasym=F in VMEC and try again.")

    # Extract mode numbers
    xm = vs.xm
    xn = vs.xn
    mpol = getattr(vmec.wout, 'mpol')
    ntor = getattr(vmec.wout, 'ntor')
    nfp = vmec.wout.nfp if hasattr(vmec.wout, 'nfp') else 1

    # Resulting files
    folder_list = []
    for s in s_target:
        # Construct new surface
        rmnc = np.array([f(s) for f in vs.rmnc])
        zmns = np.array([f(s) for f in vs.zmns])
        if lasym:
            rmns = np.array([f(s) for f in vs.rmns])
            zbcc = np.array([f(s) for f in vs.zbcc])

        # Axis properties 
        Raxis_cos = getattr(vmec.wout, 'raxis_cc')
        Zaxis_sin = getattr(vmec.wout, 'zaxis_cs')
        if lasym:
            Raxis_sin = getattr(vmec.wout, 'raxis_cs')
            Zaxis_cos = getattr(vmec.wout, 'zaxis_cc')
            
        # Magnetic flux
        phiedge = float(getattr(vmec.wout, 'phiedge', 1.0)) * s

        # Make input file
        params = {"lasym": lasym, 
                "nfp": nfp, 
                "mpol": mpol, 
                "ntor": ntor, 
                "phiedge": phiedge}
        
        comments = "Precise QA equilibrium generated at s = "+str(s)
        new_input_file = f"input.downsampled_{wout_name}_s_target_{s:.2f}"

        # Father folder
        dir = target_dir + f"regcoil_scan_results_{wout_name}_s_target_{s:.2f}/"
        if not os.path.exists(dir):
            os.makedirs(dir)
        folder_list.append(dir)
        # Output file
        new_input_file = dir + new_input_file
        write_vmec_input_from_coeffs(new_input_file, xm, xn, rmnc, zmns, Raxis_cos, Zaxis_sin, nfp, params=params, comments = "")

    return folder_list


def main():
    # New input file
    s_target = 0.12
    new_input_file = f"input.downsampled_preciseQAs_target_{s_target:.2f}"

    # Load reference precise QA
    vmec_file = "/home/erodrigu/Python/configs/wout_preciseQA.nc"
    vmec = Vmec(vmec_file)
    vs = vmec_splines(vmec)
    print(f"Number of surfaces: {vmec.wout.ns}")

    # Stellarator symmetry
    lasym = getattr(vmec.wout, 'lasym', False)
    if lasym:
        raise NotImplementedError("This script currently only supports stellarator-symmetric configurations. Please set lasym=F in VMEC and try again.")

    # Extract mode numbers
    xm = vs.xm
    xn = vs.xn
    mpol = getattr(vmec.wout, 'mpol')
    ntor = getattr(vmec.wout, 'ntor')
    nfp = vmec.wout.nfp if hasattr(vmec.wout, 'nfp') else 1

    # Construct new surface
    rmnc = np.array([f(s_target) for f in vs.rmnc])
    zmns = np.array([f(s_target) for f in vs.zmns])
    if lasym:
        rmns = np.array([f(s_target) for f in vs.rmns])
        zbcc = np.array([f(s_target) for f in vs.zbcc])

    # Axis properties 
    Raxis_cos = getattr(vmec.wout, 'raxis_cc')
    Zaxis_sin = getattr(vmec.wout, 'zaxis_cs')
    if lasym:
        Raxis_sin = getattr(vmec.wout, 'raxis_cs')
        Zaxis_cos = getattr(vmec.wout, 'zaxis_cc')
        
    # Magnetic flux
    phiedge = float(getattr(vmec.wout, 'phiedge', 1.0)) * s_target

    # Make input file
    params = {"lasym": lasym, 
              "nfp": nfp, 
              "mpol": mpol, 
              "ntor": ntor, 
              "phiedge": phiedge}
    
    coments = "Precise QA equilibrium generated at s = "+str(s_target)
    write_vmec_input_from_coeffs(new_input_file, xm, xn, rmnc, zmns, Raxis_cos, Zaxis_sin, nfp, params=params, comments = "")

if __name__ == "__main__":
    main()